apiVersion: v1
kind: PersistentVolume
metadata:
  name: primary-data-pv
  labels:
    io.kompose.service: primary-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/pg-primary
  claimRef:
    name: primary-data
    namespace: default
