apiVersion: v1
kind: PersistentVolume
metadata:
  name: replica-data2-pv
  labels:
    io.kompose.service: replica-data2
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/pg-replica2
  claimRef:
    name: replica-data2
    namespace: default
